project_name: GyMera接口

# 测试人员名称，作用于自动生成代码的作者，以及发送企业微信、钉钉通知的测试负责人
tester_name: 七月

env:
  # test
  host: http://192.168.5.210:9000
  user_name: 'test'
  password: '0d17cf12f54e711b'
  gymer_id: 'USR22082018194900001003CB70029'

#  user_name: '18600000000@163.com'
#  password: 'cc7b54ca81698152'
#  gymer_id: 'USR22082018194900001003CB70029'
  env_name: 测试环境--master分支
  mysql_db:
    # 数据库开关
    switch: true
    host: 192.168.5.210
    user: root
    password: '8dc1c56e7eaddc87'
    port: 3309
    database: "gymera"

    # 开发
#    host: http://192.168.5.200:9000
#    mysql_db:
#      # 数据库开关
#      switch: true
#      host: 192.168.5.200
#      user: root
#      password: '099958c41cde27b3'
#      port: 3309
#      database: "gymera"

    # 专线
#    host: http://120.237.115.66:9000
#    user_name: '15992906815'
#    password: 'a3232489'
#    gymer_id: 'USR22082018194900001003CB70029'
#    mysql_db:
#      # 数据库开关
#      switch: true
#      host: 192.168.5.200
#      user: root
#      password: '099958c41cde27b3'
#      port: 3309
#      database: "gymera"


# 域名2，支持多个域名配置
app_host:

# 实时更新用例内容，False时，已生成的代码不会在做变更
# 设置为True的时候，修改yaml文件的用例，代码中的内容会实时更新
real_time_update_test_cases: true

# 报告通知类型：0: 不发送通知 1：钉钉 2：企业微信通知 3、邮箱通知 4、飞书通知
notification_type: 3
# 收集失败的用例开关，整理成excel报告的形式，自动发送，目前只支持返送企业微信通知
excel_report: False

# 钉钉相关配置
ding_talk:
  webhook: https://oapi.dingtalk.com/robot/send?access_token=68b08cda77fab2b04a895a798c4cfa99270bc4d189aeb7dffff590785d6e6d28
#  secret: SECdea6489dfcc3b9259da943c5ae38d3530696f2fa83ac72a9ee716e9511675b9b


# 镜像源
mirror_source: http://mirrors.aliyun.com/pypi/simple/

# 企业通知的相关配置
wechat:
  webhook: https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=22748687-fa3b-4e48-a5d7-0502cef422b4


### 邮箱必填，需要全部都配置好，程序运行失败时，会发送邮件通知
email:
  send_user: ganyuhao@gymera.net
  email_host: smtp.exmail.qq.com
  # 自己到QQ邮箱中配置stamp_key
  stamp_key: Gyh3232489
  # 收件人改成自己的邮箱
  send_list: ganyuhao@gymera.net

# 飞书通知
lark:
  webhook:



